// 37 个内置品牌——源：用户 Excel 初始化数据（样例/初始化数据.xlsx）42 行拆国去重
// 拆国前缀：香港→中国香港/美国/加拿大/台湾→中国台湾/法国/日本/韩国/挪威；国家列优先于名字前缀
// 去重：名字归一（去前缀、小写、去空格）相同即合并，保留国家信息更完整者；Swerl Coffee 国别未识别留空
// description 为统一占位，后续经 admin.reinitBrands 以 AI 文案覆盖（清单：docs/品牌重初始化清单.txt）
module.exports = [
  { name: 'Moonway Coffee', nameEn: '', logo: '', country: '中国香港', description: '精品咖啡烘焙品牌', isBuiltin: true, aliases: [] },
  { name: 'SEY', nameEn: '', logo: '', country: '美国', description: '精品咖啡烘焙品牌', isBuiltin: true, aliases: [] },
  { name: 'Monogram', nameEn: '', logo: '', country: '加拿大', description: '精品咖啡烘焙品牌', isBuiltin: true, aliases: [] },
  { name: '云林ludan coffee', nameEn: '', logo: '', country: '中国台湾', description: '精品咖啡烘焙品牌', isBuiltin: true, aliases: [] },
  { name: 'OMA', nameEn: '', logo: '', country: '中国香港', description: '精品咖啡烘焙品牌', isBuiltin: true, aliases: [] },
  { name: 'Hexagone', nameEn: '', logo: '', country: '法国', description: '精品咖啡烘焙品牌', isBuiltin: true, aliases: [] },
  { name: 'RightPaw', nameEn: '', logo: '', country: '中国', description: '精品咖啡烘焙品牌', isBuiltin: true, aliases: [] },
  { name: 'Weekenders', nameEn: '', logo: '', country: '日本', description: '精品咖啡烘焙品牌', isBuiltin: true, aliases: [] },
  { name: 'MOMOS', nameEn: '', logo: '', country: '韩国', description: '精品咖啡烘焙品牌', isBuiltin: true, aliases: [] },
  { name: 'tim wendelboe', nameEn: '', logo: '', country: '挪威', description: '精品咖啡烘焙品牌', isBuiltin: true, aliases: [] },
  { name: 'Rki Coffee', nameEn: '', logo: '', country: '加拿大', description: '精品咖啡烘焙品牌', isBuiltin: true, aliases: [] },
  { name: 'Commodore Coffee', nameEn: '', logo: '', country: '中国', description: '精品咖啡烘焙品牌', isBuiltin: true, aliases: [] },
  { name: '炸帽FIREHAT', nameEn: '', logo: '', country: '荷兰', description: '精品咖啡烘焙品牌', isBuiltin: true, aliases: [] },
  { name: '奶嘴NAIZUI', nameEn: '', logo: '', country: '中国', description: '精品咖啡烘焙品牌', isBuiltin: true, aliases: [] },
  { name: 'September', nameEn: '', logo: '', country: '加拿大', description: '精品咖啡烘焙品牌', isBuiltin: true, aliases: [] },
  { name: 'Subtext', nameEn: '', logo: '', country: '加拿大', description: '精品咖啡烘焙品牌', isBuiltin: true, aliases: [] },
  { name: 'Sherry Selection', nameEn: '', logo: '', country: '中国台湾', description: '精品咖啡烘焙品牌', isBuiltin: true, aliases: [] },
  { name: 'Solkatt Coffee', nameEn: '', logo: '', country: '捷克', description: '精品咖啡烘焙品牌', isBuiltin: true, aliases: [] },
  { name: 'Style Coffee', nameEn: '', logo: '', country: '日本', description: '精品咖啡烘焙品牌', isBuiltin: true, aliases: [] },
  { name: 'Swerl Coffee', nameEn: '', logo: '', country: '', description: '精品咖啡烘焙品牌', isBuiltin: true, aliases: [] },
  { name: 'Casino Mocca', nameEn: '', logo: '', country: '捷克', description: '精品咖啡烘焙品牌', isBuiltin: true, aliases: [] },
  { name: '白鲸咖啡', nameEn: 'MOBYDICK COFFEE ROASTERS', logo: '', country: '中国', description: '精品咖啡烘焙品牌', isBuiltin: true, aliases: ['MOBYDICK', 'YELEI LAB', '白鲸'] },
  { name: '乔治队长', nameEn: '', logo: '', country: '中国', description: '精品咖啡烘焙品牌', isBuiltin: true, aliases: [] },
  { name: 'Terraform啟程拓殖', nameEn: '', logo: '', country: '中国', description: '精品咖啡烘焙品牌', isBuiltin: true, aliases: [] },
  { name: '海娟家', nameEn: '', logo: '', country: '美国', description: '精品咖啡烘焙品牌', isBuiltin: true, aliases: [] },
  { name: 'sweetness coffee lab', nameEn: '', logo: '', country: '韩国', description: '精品咖啡烘焙品牌', isBuiltin: true, aliases: [] },
  { name: '尽力而为', nameEn: '', logo: '', country: '中国', description: '精品咖啡烘焙品牌', isBuiltin: true, aliases: [] },
  { name: 'underbean', nameEn: '', logo: '', country: '韩国', description: '精品咖啡烘焙品牌', isBuiltin: true, aliases: [] },
  { name: 'Traffic Coffee', nameEn: '', logo: '', country: '加拿大', description: '精品咖啡烘焙品牌', isBuiltin: true, aliases: [] },
  { name: 'Preface coffee', nameEn: '', logo: '', country: '美国', description: '精品咖啡烘焙品牌', isBuiltin: true, aliases: [] },
  { name: 'SANDBOK COFFEE ROASTERS', nameEn: '', logo: '', country: '德国', description: '精品咖啡烘焙品牌', isBuiltin: true, aliases: [] },
  { name: 'malic coffee', nameEn: '', logo: '', country: '韩国', description: '精品咖啡烘焙品牌', isBuiltin: true, aliases: [] },
  { name: '魏云峰', nameEn: '', logo: '', country: '中国', description: '精品咖啡烘焙品牌', isBuiltin: true, aliases: [] },
  { name: 'SAVAGE COFFEES', nameEn: '', logo: '', country: '巴拿马', description: '精品咖啡烘焙品牌', isBuiltin: true, aliases: [] },
  { name: '青岛领地', nameEn: '', logo: '', country: '中国', description: '精品咖啡烘焙品牌', isBuiltin: true, aliases: [] },
  { name: 'MEL COFFEE', nameEn: '', logo: '', country: '日本', description: '精品咖啡烘焙品牌', isBuiltin: true, aliases: [] },
  { name: 'Prodigal Coffee', nameEn: '', logo: '', country: '美国', description: '精品咖啡烘焙品牌', isBuiltin: true, aliases: [] },
];
