// 预置风味标签 149 个 = 规格书 3.6 内置 45 + 用户 Excel 初始化数据合并新增 104
// Excel 119 条：精确同名去重后与内置 45 按 name 合并（茉莉/茉莉花、蓝莓/成熟蓝莓等修饰词差异保留为独立条目）
// 归类：浆果柑橘核果热带果汁→水果类；花→花香类；蜂蜜糖浆果酱糖果冰糖蜂巢→甜感类
//      茶饮（红茶/大吉岭茶/伯爵茶/高山茶/四季春/茉莉花茶/蜜桃茶/小青柑）与口感词（丝滑口感/多汁/复杂）→其他
// emoji 为占位，iconUrl 留空；本轮不调用 genFlavorIcon 生图，后续按需补图标
module.exports = [
  // 水果类（12）
  { _id: 'f01', name: '草莓', category: '水果类', iconUrl: '', emoji: '🍓', isBuiltin: true },
  { _id: 'f02', name: '橙子', category: '水果类', iconUrl: '', emoji: '🍊', isBuiltin: true },
  { _id: 'f03', name: '柠檬', category: '水果类', iconUrl: '', emoji: '🍋', isBuiltin: true },
  { _id: 'f04', name: '蓝莓', category: '水果类', iconUrl: '', emoji: '🫐', isBuiltin: true },
  { _id: 'f05', name: '桃子', category: '水果类', iconUrl: '', emoji: '🍑', isBuiltin: true },
  { _id: 'f06', name: '芒果', category: '水果类', iconUrl: '', emoji: '🥭', isBuiltin: true },
  { _id: 'f07', name: '菠萝', category: '水果类', iconUrl: '', emoji: '🍍', isBuiltin: true },
  { _id: 'f08', name: '苹果', category: '水果类', iconUrl: '', emoji: '🍎', isBuiltin: true },
  { _id: 'f09', name: '葡萄', category: '水果类', iconUrl: '', emoji: '🍇', isBuiltin: true },
  { _id: 'f10', name: '樱桃', category: '水果类', iconUrl: '', emoji: '🍒', isBuiltin: true },
  { _id: 'f11', name: '百香果', category: '水果类', iconUrl: '', emoji: '🟣', isBuiltin: true },
  { _id: 'f12', name: '猕猴桃', category: '水果类', iconUrl: '', emoji: '🥝', isBuiltin: true },
  // 花香类（6）
  { _id: 'f13', name: '茉莉', category: '花香类', iconUrl: '', emoji: '🤍', isBuiltin: true },
  { _id: 'f14', name: '玫瑰', category: '花香类', iconUrl: '', emoji: '🌹', isBuiltin: true },
  { _id: 'f15', name: '桂花', category: '花香类', iconUrl: '', emoji: '🌼', isBuiltin: true },
  { _id: 'f16', name: '洋甘菊', category: '花香类', iconUrl: '', emoji: '🌸', isBuiltin: true },
  { _id: 'f17', name: '薰衣草', category: '花香类', iconUrl: '', emoji: '💜', isBuiltin: true },
  { _id: 'f18', name: '橙花', category: '花香类', iconUrl: '', emoji: '🌼', isBuiltin: true },
  // 甜感类（6）
  { _id: 'f19', name: '蜂蜜', category: '甜感类', iconUrl: '', emoji: '🍯', isBuiltin: true },
  { _id: 'f20', name: '焦糖', category: '甜感类', iconUrl: '', emoji: '🍬', isBuiltin: true },
  { _id: 'f21', name: '香草', category: '甜感类', iconUrl: '', emoji: '🌿', isBuiltin: true },
  { _id: 'f22', name: '红糖', category: '甜感类', iconUrl: '', emoji: '🟤', isBuiltin: true },
  { _id: 'f23', name: '糖蜜', category: '甜感类', iconUrl: '', emoji: '🟫', isBuiltin: true },
  { _id: 'f24', name: '枫糖', category: '甜感类', iconUrl: '', emoji: '🥞', isBuiltin: true },
  // 坚果可可类（6）
  { _id: 'f25', name: '榛子', category: '坚果可可类', iconUrl: '', emoji: '🌰', isBuiltin: true },
  { _id: 'f26', name: '杏仁', category: '坚果可可类', iconUrl: '', emoji: '🥜', isBuiltin: true },
  { _id: 'f27', name: '黑巧', category: '坚果可可类', iconUrl: '', emoji: '🍫', isBuiltin: true },
  { _id: 'f28', name: '牛奶巧克力', category: '坚果可可类', iconUrl: '', emoji: '🍫', isBuiltin: true },
  { _id: 'f29', name: '花生', category: '坚果可可类', iconUrl: '', emoji: '🥜', isBuiltin: true },
  { _id: 'f30', name: '椰子', category: '坚果可可类', iconUrl: '', emoji: '🥥', isBuiltin: true },
  // 香料类（5）
  { _id: 'f31', name: '胡椒', category: '香料类', iconUrl: '', emoji: '⚫', isBuiltin: true },
  { _id: 'f32', name: '丁香', category: '香料类', iconUrl: '', emoji: '🟤', isBuiltin: true },
  { _id: 'f33', name: '肉豆蔻', category: '香料类', iconUrl: '', emoji: '🌰', isBuiltin: true },
  { _id: 'f34', name: '肉桂', category: '香料类', iconUrl: '', emoji: '🟫', isBuiltin: true },
  { _id: 'f35', name: '八角', category: '香料类', iconUrl: '', emoji: '⭐', isBuiltin: true },
  // 烘焙类（5）
  { _id: 'f36', name: '麦芽', category: '烘焙类', iconUrl: '', emoji: '🌾', isBuiltin: true },
  { _id: 'f37', name: '谷物', category: '烘焙类', iconUrl: '', emoji: '🌾', isBuiltin: true },
  { _id: 'f38', name: '烟熏', category: '烘焙类', iconUrl: '', emoji: '💨', isBuiltin: true },
  { _id: 'f39', name: '烤可可', category: '烘焙类', iconUrl: '', emoji: '🟤', isBuiltin: true },
  { _id: 'f40', name: '饼干', category: '烘焙类', iconUrl: '', emoji: '🍪', isBuiltin: true },
  // 其他（5）
  { _id: 'f41', name: '茶感', category: '其他', iconUrl: '', emoji: '🍵', isBuiltin: true },
  { _id: 'f42', name: '奶油', category: '其他', iconUrl: '', emoji: '🥛', isBuiltin: true },
  { _id: 'f43', name: '发酵感', category: '其他', iconUrl: '', emoji: '🍶', isBuiltin: true },
  { _id: 'f44', name: '草本', category: '其他', iconUrl: '', emoji: '🌿', isBuiltin: true },
  { _id: 'f45', name: '清爽', category: '其他', iconUrl: '', emoji: '💧', isBuiltin: true },
  // ===== 以下 104 条来自用户 Excel 初始化数据（与内置 45 按 name 去重后新增） =====
  // 水果类（+62）
  { _id: 'f46', name: '莓果', category: '水果类', iconUrl: '', emoji: '🫐', isBuiltin: true },
  { _id: 'f47', name: '黑莓', category: '水果类', iconUrl: '', emoji: '🫐', isBuiltin: true },
  { _id: 'f48', name: '甜橙', category: '水果类', iconUrl: '', emoji: '🍊', isBuiltin: true },
  { _id: 'f49', name: '柑橘', category: '水果类', iconUrl: '', emoji: '🍊', isBuiltin: true },
  { _id: 'f50', name: '红梅', category: '水果类', iconUrl: '', emoji: '🍒', isBuiltin: true },
  { _id: 'f51', name: '蜜饯草莓', category: '水果类', iconUrl: '', emoji: '🍓', isBuiltin: true },
  { _id: 'f52', name: '白葡萄', category: '水果类', iconUrl: '', emoji: '🍇', isBuiltin: true },
  { _id: 'f53', name: '橘子', category: '水果类', iconUrl: '', emoji: '🍊', isBuiltin: true },
  { _id: 'f54', name: '红醋栗', category: '水果类', iconUrl: '', emoji: '🍒', isBuiltin: true },
  { _id: 'f55', name: '树莓', category: '水果类', iconUrl: '', emoji: '🍓', isBuiltin: true },
  { _id: 'f56', name: '黄桃', category: '水果类', iconUrl: '', emoji: '🍑', isBuiltin: true },
  { _id: 'f57', name: '西瓜', category: '水果类', iconUrl: '', emoji: '🍉', isBuiltin: true },
  { _id: 'f58', name: '佛手柑', category: '水果类', iconUrl: '', emoji: '🍋', isBuiltin: true },
  { _id: 'f59', name: '蜜瓜', category: '水果类', iconUrl: '', emoji: '🍈', isBuiltin: true },
  { _id: 'f60', name: '荔枝', category: '水果类', iconUrl: '', emoji: '🍒', isBuiltin: true },
  { _id: 'f61', name: '成熟蓝莓', category: '水果类', iconUrl: '', emoji: '🫐', isBuiltin: true },
  { _id: 'f62', name: '李子', category: '水果类', iconUrl: '', emoji: '🟣', isBuiltin: true },
  { _id: 'f63', name: '核果', category: '水果类', iconUrl: '', emoji: '🍑', isBuiltin: true },
  { _id: 'f64', name: '黄柠檬', category: '水果类', iconUrl: '', emoji: '🍋', isBuiltin: true },
  { _id: 'f65', name: '蜜柑', category: '水果类', iconUrl: '', emoji: '🍊', isBuiltin: true },
  { _id: 'f66', name: '混合浆果', category: '水果类', iconUrl: '', emoji: '🫐', isBuiltin: true },
  { _id: 'f67', name: '黑樱桃', category: '水果类', iconUrl: '', emoji: '🍒', isBuiltin: true },
  { _id: 'f68', name: '热带水果', category: '水果类', iconUrl: '', emoji: '🥭', isBuiltin: true },
  { _id: 'f69', name: '成熟热带水果', category: '水果类', iconUrl: '', emoji: '🥭', isBuiltin: true },
  { _id: 'f70', name: '杏子', category: '水果类', iconUrl: '', emoji: '🍑', isBuiltin: true },
  { _id: 'f71', name: '油桃', category: '水果类', iconUrl: '', emoji: '🍑', isBuiltin: true },
  { _id: 'f72', name: '青柠檬汁', category: '水果类', iconUrl: '', emoji: '🍋', isBuiltin: true },
  { _id: 'f73', name: '白桃', category: '水果类', iconUrl: '', emoji: '🍑', isBuiltin: true },
  { _id: 'f74', name: '青提', category: '水果类', iconUrl: '', emoji: '🍇', isBuiltin: true },
  { _id: 'f75', name: '橙汁', category: '水果类', iconUrl: '', emoji: '🍊', isBuiltin: true },
  { _id: 'f76', name: '柠檬水', category: '水果类', iconUrl: '', emoji: '🍋', isBuiltin: true },
  { _id: 'f77', name: '青柠', category: '水果类', iconUrl: '', emoji: '🍋', isBuiltin: true },
  { _id: 'f78', name: '明亮柑橘酸质', category: '水果类', iconUrl: '', emoji: '🍊', isBuiltin: true },
  { _id: 'f79', name: '葡萄柚', category: '水果类', iconUrl: '', emoji: '🍊', isBuiltin: true },
  { _id: 'f80', name: '杨桃', category: '水果类', iconUrl: '', emoji: '⭐', isBuiltin: true },
  { _id: 'f81', name: '香梨', category: '水果类', iconUrl: '', emoji: '🍐', isBuiltin: true },
  { _id: 'f82', name: '杏桃', category: '水果类', iconUrl: '', emoji: '🍑', isBuiltin: true },
  { _id: 'f83', name: '黑醋栗', category: '水果类', iconUrl: '', emoji: '🫐', isBuiltin: true },
  { _id: 'f84', name: '杏', category: '水果类', iconUrl: '', emoji: '🍑', isBuiltin: true },
  { _id: 'f85', name: '樱桃利口酒', category: '水果类', iconUrl: '', emoji: '🍒', isBuiltin: true },
  { _id: 'f86', name: '山竹', category: '水果类', iconUrl: '', emoji: '🟣', isBuiltin: true },
  { _id: 'f87', name: '水蜜桃', category: '水果类', iconUrl: '', emoji: '🍑', isBuiltin: true },
  { _id: 'f88', name: '血橙', category: '水果类', iconUrl: '', emoji: '🍊', isBuiltin: true },
  { _id: 'f89', name: '盐渍李子', category: '水果类', iconUrl: '', emoji: '🟣', isBuiltin: true },
  { _id: 'f90', name: '葡萄汁', category: '水果类', iconUrl: '', emoji: '🍇', isBuiltin: true },
  { _id: 'f91', name: '麝香玫瑰葡萄', category: '水果类', iconUrl: '', emoji: '🍇', isBuiltin: true },
  { _id: 'f92', name: '杏儿', category: '水果类', iconUrl: '', emoji: '🍑', isBuiltin: true },
  { _id: 'f93', name: '成熟莓果', category: '水果类', iconUrl: '', emoji: '🫐', isBuiltin: true },
  { _id: 'f94', name: '粉红柠檬水', category: '水果类', iconUrl: '', emoji: '🍋', isBuiltin: true },
  { _id: 'f95', name: '橙皮', category: '水果类', iconUrl: '', emoji: '🍊', isBuiltin: true },
  { _id: 'f96', name: '水果', category: '水果类', iconUrl: '', emoji: '🍎', isBuiltin: true },
  { _id: 'f97', name: '脐橙', category: '水果类', iconUrl: '', emoji: '🍊', isBuiltin: true },
  { _id: 'f98', name: '覆盆子', category: '水果类', iconUrl: '', emoji: '🍓', isBuiltin: true },
  { _id: 'f99', name: '红樱桃', category: '水果类', iconUrl: '', emoji: '🍒', isBuiltin: true },
  { _id: 'f100', name: '西柚', category: '水果类', iconUrl: '', emoji: '🍊', isBuiltin: true },
  { _id: 'f101', name: '酸橙', category: '水果类', iconUrl: '', emoji: '🍋', isBuiltin: true },
  { _id: 'f102', name: '柳橙', category: '水果类', iconUrl: '', emoji: '🍊', isBuiltin: true },
  { _id: 'f103', name: '混合莓果', category: '水果类', iconUrl: '', emoji: '🫐', isBuiltin: true },
  { _id: 'f104', name: '无花果', category: '水果类', iconUrl: '', emoji: '🍐', isBuiltin: true },
  { _id: 'f105', name: '针叶樱桃', category: '水果类', iconUrl: '', emoji: '🍒', isBuiltin: true },
  { _id: 'f106', name: '香橙', category: '水果类', iconUrl: '', emoji: '🍊', isBuiltin: true },
  { _id: 'f107', name: '番石榴', category: '水果类', iconUrl: '', emoji: '🍈', isBuiltin: true },
  // 花香类（+16）
  { _id: 'f108', name: '花香', category: '花香类', iconUrl: '', emoji: '🌸', isBuiltin: true },
  { _id: 'f109', name: '茉莉花', category: '花香类', iconUrl: '', emoji: '🤍', isBuiltin: true },
  { _id: 'f110', name: '浓郁橙花', category: '花香类', iconUrl: '', emoji: '🌼', isBuiltin: true },
  { _id: 'f111', name: '鸡蛋花', category: '花香类', iconUrl: '', emoji: '🌼', isBuiltin: true },
  { _id: 'f112', name: '花朵', category: '花香类', iconUrl: '', emoji: '🌸', isBuiltin: true },
  { _id: 'f113', name: '洛神花', category: '花香类', iconUrl: '', emoji: '🌺', isBuiltin: true },
  { _id: 'f114', name: '白色花', category: '花香类', iconUrl: '', emoji: '🤍', isBuiltin: true },
  { _id: 'f115', name: '玫瑰花香', category: '花香类', iconUrl: '', emoji: '🌹', isBuiltin: true },
  { _id: 'f116', name: '花卉', category: '花香类', iconUrl: '', emoji: '🌸', isBuiltin: true },
  { _id: 'f117', name: '紫色花朵', category: '花香类', iconUrl: '', emoji: '💜', isBuiltin: true },
  { _id: 'f118', name: '玫瑰果', category: '花香类', iconUrl: '', emoji: '🌹', isBuiltin: true },
  { _id: 'f119', name: '红玫瑰', category: '花香类', iconUrl: '', emoji: '🌹', isBuiltin: true },
  { _id: 'f120', name: '白色花香', category: '花香类', iconUrl: '', emoji: '🤍', isBuiltin: true },
  { _id: 'f121', name: '百合花', category: '花香类', iconUrl: '', emoji: '🌼', isBuiltin: true },
  { _id: 'f122', name: '姜花', category: '花香类', iconUrl: '', emoji: '🌼', isBuiltin: true },
  { _id: 'f123', name: '白花', category: '花香类', iconUrl: '', emoji: '🤍', isBuiltin: true },
  // 甜感类（+8）
  { _id: 'f124', name: '果酱', category: '甜感类', iconUrl: '', emoji: '🍯', isBuiltin: true },
  { _id: 'f125', name: '甘蔗清甜', category: '甜感类', iconUrl: '', emoji: '🎋', isBuiltin: true },
  { _id: 'f126', name: '桃子软糖', category: '甜感类', iconUrl: '', emoji: '🍬', isBuiltin: true },
  { _id: 'f127', name: '蔗糖', category: '甜感类', iconUrl: '', emoji: '🍬', isBuiltin: true },
  { _id: 'f128', name: '蜂巢', category: '甜感类', iconUrl: '', emoji: '🍯', isBuiltin: true },
  { _id: 'f129', name: '柠檬糖', category: '甜感类', iconUrl: '', emoji: '🍬', isBuiltin: true },
  { _id: 'f130', name: '冰糖', category: '甜感类', iconUrl: '', emoji: '🧊', isBuiltin: true },
  { _id: 'f131', name: '蜂蜜甜感', category: '甜感类', iconUrl: '', emoji: '🍯', isBuiltin: true },
  // 坚果可可类（+1）
  { _id: 'f132', name: '巧克力', category: '坚果可可类', iconUrl: '', emoji: '🍫', isBuiltin: true },
  // 香料类（+2）
  { _id: 'f133', name: '柠檬百里香', category: '香料类', iconUrl: '', emoji: '🌿', isBuiltin: true },
  { _id: 'f134', name: '生姜', category: '香料类', iconUrl: '', emoji: '🫚', isBuiltin: true },
  // 烘焙类（+1）
  { _id: 'f135', name: '桃子挞', category: '烘焙类', iconUrl: '', emoji: '🥧', isBuiltin: true },
  // 其他（+14：茶饮 + 口感词 + 酒饮/创意词）
  { _id: 'f136', name: '红茶', category: '其他', iconUrl: '', emoji: '🫖', isBuiltin: true },
  { _id: 'f137', name: '多汁', category: '其他', iconUrl: '', emoji: '💧', isBuiltin: true },
  { _id: 'f138', name: '茉莉花茶', category: '其他', iconUrl: '', emoji: '🍵', isBuiltin: true },
  { _id: 'f139', name: '大吉岭茶', category: '其他', iconUrl: '', emoji: '🫖', isBuiltin: true },
  { _id: 'f140', name: '蜜桃茶', category: '其他', iconUrl: '', emoji: '🍑', isBuiltin: true },
  { _id: 'f141', name: '丝滑口感', category: '其他', iconUrl: '', emoji: '🥛', isBuiltin: true },
  { _id: 'f142', name: '四季春', category: '其他', iconUrl: '', emoji: '🍵', isBuiltin: true },
  { _id: 'f143', name: '桃红葡萄酒', category: '其他', iconUrl: '', emoji: '🍷', isBuiltin: true },
  { _id: 'f144', name: '椰奶般的奶油质感', category: '其他', iconUrl: '', emoji: '🥛', isBuiltin: true },
  { _id: 'f145', name: '伯爵茶', category: '其他', iconUrl: '', emoji: '🫖', isBuiltin: true },
  { _id: 'f146', name: '高山茶', category: '其他', iconUrl: '', emoji: '🍵', isBuiltin: true },
  { _id: 'f147', name: '小青柑', category: '其他', iconUrl: '', emoji: '🍵', isBuiltin: true },
  { _id: 'f148', name: '夏日风暴', category: '其他', iconUrl: '', emoji: '⛈️', isBuiltin: true },
  { _id: 'f149', name: '复杂', category: '其他', iconUrl: '', emoji: '🌀', isBuiltin: true },
];
